- name: update windows systems
  hosts: all
  gather_facts: False
  become: no
  vars:
    win_update_category_names:
      - CriticalUpdates
      - DefinitionUpdates
      - SecurityUpdates
      - UpdateRollups
      - Updates     
  roles:
    - oatakan.windows_update
