---
- name: Update Windows systems
  hosts: windows_hosts
  gather_facts: false
  become: yes

  tasks:
    - name: Check for Windows updates
      win_updates:
        category_names:
          - CriticalUpdates
          - SecurityUpdates
          - UpdateRollups
          - ServicePacks
          - DefinitionUpdates
        state: searched
      register: update_result

    - name: Install Windows updates
      win_updates:
        category_names:
          - CriticalUpdates
          - SecurityUpdates
          - UpdateRollups
          - ServicePacks
          - DefinitionUpdates
        state: installed
      when: update_result.updates | length > 0
